CREATE TABLE ROLES (
  ID BIGINT PRIMARY KEY AUTO_INCREMENT,
  ROLE_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE USERS_TO_ROLES (
  FK_USER_ID BIGINT NOT NULL,
  FK_ROLE_ID BIGINT NOT NULL,
  CONSTRAINT FK_UTR_USERS2 FOREIGN KEY (FK_ROLE_ID)
    REFERENCES USERS(ID),
  CONSTRAINT FK_UTR_ROLES2 FOREIGN KEY (FK_ROLE_ID)
    REFERENCES ROLES(ID)
);

INSERT INTO USERS_TO_ROLES VALUES (1, 2);
INSERT INTO USERS_TO_ROLES VALUES (1, 2);
INSERT INTO USERS_TO_ROLES VALUES (1, 3);